server:
  port: 0
spring:
  application:
    name: service-client
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/service-client
    username: root
    password: